version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend
    env_file: .env
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - STATIC_ROOT=/backend_static/static
      - MEDIA_ROOT=/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
